/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package pl.futurecollars.invoicing;

import pl.futurecollars.invoicing.model.User;

public class App {

  public String getGreeting() {

    User user = User.builder()
        .name("konrad")
        .build();

    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }

}
